name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  install:
    runs-on: ubuntu-latest

    container:
      image: node:22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: npm install

  setup-config:
    needs: install
    runs-on: ubuntu-latest

    container:
      image: node:22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup config files
        run: |
          mkdir -p config
          echo '{
            "port": 5003,
            "myAddress": "http://localhost",
            "corsOrigin": ["http://localhost"],
            "trustProxy": false,
            "repository": "postgres",
            "postgres": {
              "user": "postgresUser",
              "password": "postgresPass",
              "host": "postgres",
              "db": "monsters_test",
              "port": 5432
            },
            "diagnostics": {
              "reqTime": false,
              "logRequests": false
            }
          }' > config/devConfig.json
          cp config/devConfig.json config/prodConfig.json
          cp config/devConfig.json config/testConfig.json

      - name: Upload config
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: config/

  test:
    needs: [setup-config]
    runs-on: ubuntu-latest

    container:
      image: node:22

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgresUser
          POSTGRES_PASSWORD: postgresPass
          POSTGRES_DB: monsters_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Download config
        uses: actions/download-artifact@v4
        with:
          name: config
          path: config/

      - name: Run tests
        run: npm run test:e2e && npm run test:unit && npm run test:db

  lint:
    needs: [setup-config]
    runs-on: ubuntu-latest

    container:
      image: node:22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Download config
        uses: actions/download-artifact@v4
        with:
          name: config
          path: config/

      - name: Lint
        run: npm run lint

  build:
    needs: [setup-config, test, lint]

    runs-on: ubuntu-latest

    container:
      image: node:22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Download config
        uses: actions/download-artifact@v4
        with:
          name: config
          path: config/

      - name: Build
        run: npm run build
